name: lintfix

on:
  pull_request_target:

env:
  YARN_MODULES_CACHE_KEY: v1
  YARN_PACKAGE_CACHE_KEY: v1
  YARN_CACHE_FOLDER: .cache/yarn
  NODE_VERSION: 14
  FIX_AUTHOR_EMAIL: renovate@whitesourcesoftware.com

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    # lint shouldn't need more than 15 min
    timeout-minutes: 15

    steps:
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Init platform
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
          git config --global user.email $FIX_AUTHOR_EMAIL
          git config --global user.name 'Renovate Bot'
          npm config set scripts-prepend-node-path true
          echo "Node $(node --version)"
          echo "Yarn $(yarn --version)"

      - name: checkout base
        uses: actions/checkout@v2.3.3
        with:
          persist-credentials: false # do not persist credentials

      - name: Cache Yarn packages
        id: yarn_cache_packages
        uses: actions/cache@v2.1.2
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ env.YARN_PACKAGE_CACHE_KEY }}-${{ runner.os }}-yarn_cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.YARN_PACKAGE_CACHE_KEY }}-${{ runner.os }}-yarn_cache-

      - name: Installing dependencies
        run: yarn install --frozen-lockfile


      - name: checkout pr head
        uses: actions/checkout@v2.3.3
        with:
          persist-credentials: false # do not persist credentials
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          clean: false

      - name: Lint
        run: |
          # disable command workflow processing
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

          # lint-fix
          docker run --rm -u "$UID:0" \
           -v "${PWD}:/code" \
           -v "$(mktemp -d -t ci-XXXXXXXXXX):/code/.git:ro" \
           -v "$(mktemp -d -t ci-XXXXXXXXXX):/code/.cache:ro" \
           -v "$(mktemp -d -t ci-XXXXXXXXXX):/tmp/${UID}" \
           -w /code \
           -e HOME=/tmp/${UID} \
           "renovate/node:${{ env.NODE_VERSION}}" \
           npx yarn lint-fix

          # enable workflow command processing
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} #needs maintainer pat here to push to forks
          GIT_REPO: ${{github.event.pull_request.head.repo.full_name}}
          GIT_REF: ${{github.event.pull_request.head.ref}}
        run: |
          git config core.hooksPath $(mktemp -d -t ci-XXXXXXXXXX)
          if [[ "$(git diff --stat)" != '' && "$(git log -1 --pretty=format:'%ae')" != "${FIX_AUTHOR_EMAIL}" ]]; then
            git commit -a -m "chore: lint fix"
            git push https://${GH_TOKEN}:github.com/${GIT_REPO} ${GIT_REF}
          else
            echo 'nothing todo'
          fi
